<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM32l4Nd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM32l4Nd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM32l4Nd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM32l4Nd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM32l4Nd\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'M32l4Nd',
    'container.build_id' => '25ed31ba',
    'container.build_time' => 1544438057,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerM32l4Nd');
